apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscribermanagement
  labels:
    app: subscribermanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscribermanagement
  template:
    metadata:
      labels:
        app: subscribermanagement
        sider.istio.io/inject: "true"
    spec:
      containers:
        - name: subscribermanagement
          image: "project05.azurecr.io/subscribermanagement:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
