apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookplatform
  labels:
    app: bookplatform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookplatform
  template:
    metadata:
      labels:
        app: bookplatform
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: bookplatform
          image: "project05.azurecr.io/bookplatform:v1"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
